spring:
  application:
    name: traceK
  profiles:
    active: ${SPRING_PROFILE:local}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
app:
  jwt:
    secret: ${JWT_SECRET:default_local_secret_key_for_testing_1234567890}
    access-expiration-time: ${JWT_ACCESS_TIME:3600000}
    refresh-expiration-time: ${JWT_REFRESH_TIME:1209600000}
  auth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID:}
      redirect-uri: ${KAKAO_REDIRECT_URL:}
      client-secret: ${KAKAO_CLIENT_SECRET:}
      api-base-url: https://kapi.kakao.com
      authorization-base-url: https://kauth.kakao.com