spring:
  application:
    name: traceK
  profiles:
    active: ${SPRING_PROFILE}
app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-time: ${JWT_ACCESS_TIME}
    refresh-expiration-time: ${JWT_REFRESH_TIME}